# https://gist.github.com/alefteris/39c9cfe3a6baa9fc5acf
# https://eslint.org/docs/rules/
# https://vuejs.org/style-guide/rules-essential.html
# https://github.com/marcelmokos/eslint-config-with-prettier/blob/master/.eslintrc.yml

env:
  browser: true
  node: true

extends:
  - 'eslint:recommended'
  - 'plugin:vue/recommended'

parser: 'vue-eslint-parser'

parserOptions:
  parser: '@babel/eslint-parser'
  ecmaVersion: 8
  requireConfigFile: false
  sourceType: module
  allowImportExportEverywhere: false
  ecmaFeatures:
    jsx: false
    globalReturn: false
    impliedStrict: false

plugins:
  - vue

rules:
  vue/max-attributes-per-line: 0
  vue/singleline-html-element-content-newline: 0
  vue/attribute-hyphenation: 0
  vue/multi-word-component-names: 0
  semi:
    - 2
    - never
  keyword-spacing: 2
  no-multi-spaces: 2
  space-before-function-paren: 0
  vue/html-closing-bracket-spacing: 0
  space-before-blocks: 2
  spaced-comment: 1
  space-infix-ops: 1
  no-extra-semi: 2
  object-curly-spacing:
    - 2
    - always
  space-in-parens:
    - 1
    - never
  space-unary-ops:
    - 2
    - words: true
      nonwords: false
      overrides:
        '!': true
  indent:
    - error
    - 2
    - SwitchCase: 1
